# Generated by Django 5.0.6 on 2024-06-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userisactivecode',
            old_name='confirmation_code',
            new_name='code',
        ),
    ]
